/**
 * Report history — all published/rejected reports.
 */

export function HistoryPage() {
  const reports = [
    { id: '8e0d90b4', title: 'Portefeuille de Prêts par Agence - Dernier Trimestre', dept: 'Strategy Division', type: 'loan_portfolio', status: 'published', charts: 3, score: 1.0 },
    { id: '75316d70', title: 'Rapport loan_portfolio - Loans', dept: 'Strategy Division', type: 'loan_portfolio', status: 'published', charts: 2, score: 1.0 },
    { id: '9f1bf80e', title: 'Rapport daily_summary - Transactions', dept: 'Digital Innovation Center', type: 'daily_summary', status: 'published', charts: 2, score: 1.0 },
    { id: 'e9a2cc50', title: "Rapport d'Analyse du Portefeuille de Prêts", dept: 'Strategy Division', type: 'loan_portfolio', status: 'published', charts: 2, score: 1.0 },
    { id: 'f4dd954a', title: 'Portefeuille de Prêts par Agence', dept: 'Strategy Division', type: 'loan_portfolio', status: 'published', charts: 3, score: 1.0 },
  ];

  const statusStyle: Record<string, string> = {
    published: 'bg-sb5-green/15 text-sb5-green',
    pending: 'bg-sb5-amber/15 text-sb5-amber',
    rejected: 'bg-sb5-red/15 text-sb5-red',
  };

  return (
    <div className="flex-1 overflow-y-auto p-6">
      <h2 className="text-lg font-semibold mb-1">Report History</h2>
      <p className="text-sm text-muted-foreground mb-5">{reports.length} reports generated by the pipeline</p>

      <div className="bg-card border border-border rounded-xl overflow-hidden">
        <table className="w-full">
          <thead>
            <tr className="border-b border-border">
              <th className="text-left text-[11px] uppercase tracking-wider text-muted-foreground px-4 py-3">Report</th>
              <th className="text-left text-[11px] uppercase tracking-wider text-muted-foreground px-4 py-3">Department</th>
              <th className="text-left text-[11px] uppercase tracking-wider text-muted-foreground px-4 py-3">Type</th>
              <th className="text-center text-[11px] uppercase tracking-wider text-muted-foreground px-4 py-3">Charts</th>
              <th className="text-center text-[11px] uppercase tracking-wider text-muted-foreground px-4 py-3">Compliance</th>
              <th className="text-center text-[11px] uppercase tracking-wider text-muted-foreground px-4 py-3">Status</th>
            </tr>
          </thead>
          <tbody>
            {reports.map((r) => (
              <tr key={r.id} className="border-b border-border/50 hover:bg-secondary/30 cursor-pointer transition">
                <td className="px-4 py-3">
                  <p className="text-sm font-medium">{r.title}</p>
                  <p className="text-[10px] text-muted-foreground font-mono">{r.id}</p>
                </td>
                <td className="px-4 py-3 text-sm text-muted-foreground">{r.dept}</td>
                <td className="px-4 py-3">
                  <span className="bg-secondary px-2 py-0.5 rounded text-[11px] text-muted-foreground">{r.type}</span>
                </td>
                <td className="px-4 py-3 text-center text-sm">{r.charts}</td>
                <td className="px-4 py-3 text-center text-sm">{(r.score * 100).toFixed(0)}%</td>
                <td className="px-4 py-3 text-center">
                  <span className={`text-[11px] px-2.5 py-0.5 rounded-full font-medium ${statusStyle[r.status] || ''}`}>
                    {r.status}
                  </span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
